import PDFDocument from 'pdfkit'
import type { ItineraryContent } from './ai.service'

const FOREST = '#3D8B5E'
const SKY    = '#5B9BD5'
const SUN    = '#F5A623'
const MUTED  = '#7D8590'
const DARK   = '#0D1117'
const SURFACE= '#161B22'
const TEXT   = '#E6EDF3'

function stripEmoji(str: string): string {
  return str.replace(/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}\u{FE00}-\u{FEFF}]/gu, '').trim()
}

export async function buildItineraryPDF(
  tripName: string,
  destination: string,
  travelStart: Date | null,
  travelEnd: Date | null,
  members: string[],
  itinerary: ItineraryContent,
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50, bufferPages: true })
    const chunks: Buffer[] = []
    doc.on('data', (c) => chunks.push(c))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    const W = doc.page.width - 100  // usable width

    // Track footer text per page index
    const footers: string[] = []

    // ── Cover Page ──────────────────────────────────────────────
    doc.rect(0, 0, doc.page.width, doc.page.height).fill(DARK)
    doc.rect(0, 0, doc.page.width, 6).fill(FOREST)
    doc.circle(doc.page.width - 80, 120, 120).fillOpacity(0.04).fill(FOREST).fillOpacity(1)

    doc.fontSize(11).fillColor(FOREST).font('Helvetica-Bold')
       .text('TRIPUNTANGLE', 50, 30, { align: 'left' })

    doc.fontSize(36).fillColor(TEXT).font('Helvetica-Bold')
       .text(tripName, 50, 100, { width: W * 0.7 })

    doc.fontSize(16).fillColor(MUTED).font('Helvetica')
       .text(destination, 50, doc.y + 10)

    if (travelStart) {
      const dateStr = travelEnd
        ? `${fmtDate(travelStart)}  →  ${fmtDate(travelEnd)}`
        : fmtDate(travelStart)
      doc.fontSize(13).fillColor(SKY).font('Helvetica')
         .text(dateStr, 50, doc.y + 8)
    }

    doc.moveDown(0.5)
    doc.fontSize(12).fillColor(SUN).font('Helvetica-Oblique')
       .text(`AI Recommended: ${itinerary.recommendedDates}`, 50, doc.y)

    doc.moveTo(50, doc.y + 20).lineTo(50 + W, doc.y + 20).strokeColor(FOREST).lineWidth(1).stroke()

    doc.moveDown(2)
    doc.fontSize(10).fillColor(MUTED).font('Helvetica-Bold').text('TRAVEL CREW', 50, doc.y)
    doc.moveDown(0.4)
    members.forEach((name) => {
      doc.fontSize(12).fillColor(TEXT).font('Helvetica')
         .text(`  •  ${name}`, 50, doc.y)
    })

    doc.moveDown(1.5)
    roundedBox(doc, 50, doc.y, W, 50, SURFACE)
    doc.fontSize(11).fillColor(MUTED).font('Helvetica-Bold')
       .text('BUDGET NOTE', 65, doc.y - 42)
    doc.fontSize(11).fillColor(TEXT).font('Helvetica')
       .text(stripEmoji(itinerary.budgetNote), 65, doc.y - 26, { width: W - 30 })

    doc.moveDown(2)
    doc.fontSize(10).fillColor(MUTED).font('Helvetica-Bold').text('HOW WE BALANCED YOUR PREFERENCES', 50, doc.y)
    doc.moveDown(0.4)
    doc.fontSize(11).fillColor(TEXT).font('Helvetica')
       .text(stripEmoji(itinerary.conflictSummary), 50, doc.y, { width: W })

    footers.push('Generated by TripUntangle AI  ·  verify all details before booking')

    // ── Day Pages ────────────────────────────────────────────────
    for (const day of itinerary.days) {
      doc.addPage()
      doc.rect(0, 0, doc.page.width, doc.page.height).fill(DARK)
      doc.rect(0, 0, doc.page.width, 6).fill(FOREST)

      doc.fontSize(10).fillColor(MUTED).font('Helvetica-Bold')
         .text(`DAY ${day.dayNumber}`, 50, 30)
      doc.fontSize(24).fillColor(TEXT).font('Helvetica-Bold')
         .text(stripEmoji(day.theme), 50, 48, { width: W })

      doc.moveTo(50, doc.y + 8).lineTo(50 + W, doc.y + 8)
         .strokeColor(FOREST).lineWidth(0.5).stroke()

      let y = doc.y + 20

      const slots: Array<{ label: string; color: string }> = [
        { label: 'Morning',   color: SUN },
        { label: 'Afternoon', color: SKY },
        { label: 'Evening',   color: '#C65D7B' },
      ]
      const activities = [day.slots.morning, day.slots.afternoon, day.slots.evening]

      for (let i = 0; i < 3; i++) {
        const act = activities[i]
        const slotMeta = slots[i]
        if (!act) continue

        doc.fontSize(9).fillColor(slotMeta.color).font('Helvetica-Bold')
           .text(slotMeta.label.toUpperCase(), 50, y)
        y += 16

        doc.fontSize(14).fillColor(TEXT).font('Helvetica-Bold')
           .text(stripEmoji(act.title), 50, y, { width: W })
        y = doc.y + 4

        doc.fontSize(11).fillColor(MUTED).font('Helvetica')
           .text(stripEmoji(act.description), 50, y, { width: W })
        y = doc.y + 6

        doc.fontSize(10).fillColor(FOREST).font('Helvetica-Bold')
           .text(`${stripEmoji(act.estimatedCost)}`, 50, y, { continued: true })
        doc.fillColor(MUTED).font('Helvetica')
           .text(`   |   ${act.duration}`, { continued: false })
        y = doc.y + 4

        if (act.tips) {
          doc.fontSize(10).fillColor(SUN).font('Helvetica-Oblique')
             .text(`Tip: ${stripEmoji(act.tips)}`, 50, y, { width: W })
          y = doc.y + 4
        }

        if (i < 2) {
          doc.moveTo(50, y + 6).lineTo(50 + W, y + 6)
             .strokeColor(SURFACE).lineWidth(1).stroke()
          y += 20
        }
      }

      footers.push(`TripUntangle  ·  ${destination}  ·  Day ${day.dayNumber} of ${itinerary.days.length}`)
    }

    // ── Essential Tips Page ──────────────────────────────────────
    if (itinerary.essentialTips) {
      const tips = itinerary.essentialTips
      doc.addPage()
      doc.rect(0, 0, doc.page.width, doc.page.height).fill(DARK)
      doc.rect(0, 0, doc.page.width, 6).fill(FOREST)

      doc.fontSize(10).fillColor(MUTED).font('Helvetica-Bold').text('ESSENTIAL TIPS', 50, 30)
      doc.fontSize(24).fillColor(TEXT).font('Helvetica-Bold').text(destination, 50, 48)

      doc.moveTo(50, doc.y + 8).lineTo(50 + W, doc.y + 8)
         .strokeColor(FOREST).lineWidth(0.5).stroke()

      let ty = doc.y + 20
      const tipItems: Array<{ label: string; value: string | undefined }> = [
        { label: 'Visa',      value: tips.visa },
        { label: 'Best Time', value: tips.bestTime },
        { label: 'Transport', value: tips.transport },
        { label: 'Safety',    value: tips.safety },
        { label: 'Currency',  value: tips.currency },
      ]
      for (const t of tipItems) {
        if (!t.value) continue
        doc.fontSize(10).fillColor(SKY).font('Helvetica-Bold').text(t.label.toUpperCase(), 50, ty)
        ty += 14
        doc.fontSize(11).fillColor(TEXT).font('Helvetica').text(stripEmoji(t.value), 50, ty, { width: W })
        ty = doc.y + 12
      }
      if (tips.mustPack && tips.mustPack.length) {
        doc.fontSize(10).fillColor(SKY).font('Helvetica-Bold').text('MUST PACK', 50, ty)
        ty += 14
        doc.fontSize(11).fillColor(TEXT).font('Helvetica')
           .text(tips.mustPack.map((p) => `• ${p}`).join('   '), 50, ty, { width: W })
      }

      footers.push('Generated by TripUntangle AI  ·  verify all details before booking')
    }

    // ── Write footers on each page (avoids blank page bug) ───────
    // With bufferPages:true, switchToPage lets us write at absolute Y
    // without triggering PDFKit's auto-pagination.
    const FOOTER_Y = doc.page.height - 65  // must be < (page.height - margin=50) = ~792pt to avoid auto-pagination
    const range = doc.bufferedPageRange()
    for (let i = 0; i < range.count; i++) {
      doc.switchToPage(range.start + i)
      doc.fontSize(9).fillColor(MUTED).font('Helvetica')
         .text(footers[i] ?? '', 50, FOOTER_Y, { align: 'center', width: W, lineBreak: false })
    }

    doc.flushPages()
    doc.end()
  })
}

function roundedBox(doc: PDFKit.PDFDocument, x: number, y: number, w: number, h: number, color: string) {
  doc.roundedRect(x, y, w, h, 6).fill(color)
}

function fmtDate(d: Date) {
  return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })
}
