import { Router } from 'express'
import { createEvents } from 'ics'
import { requireAuth, type AuthRequest } from '../middleware/auth.middleware'
import { prisma } from '../lib/prisma'
import { buildItineraryPDF } from '../services/pdf.service'
import { generateOOO } from '../services/ooo.service'
import type { ItineraryContent } from '../services/ai.service'

export const exportRouter = Router()

// GET /api/trips/:id/export/pdf — download itinerary as PDF
exportRouter.get('/trips/:id/export/pdf', requireAuth, async (req: AuthRequest, res) => {
  const tripId = String(req.params.id)

  const trip = await prisma.trip.findUnique({
    where: { id: tripId },
    include: {
      members: {
        where: { inviteStatus: 'ACCEPTED' },
        include: { user: { select: { name: true } } },
      },
    },
  })
  if (!trip) { res.status(404).json({ error: 'Trip not found' }); return }

  const member = trip.members.find((m) => (m as any).userId === req.userId)
  if (!member) { res.status(403).json({ error: 'Not a member.' }); return }

  const itinerary = await prisma.itinerary.findFirst({
    where: { tripId },
    orderBy: { version: 'desc' },
  })
  if (!itinerary) { res.status(404).json({ error: 'No itinerary yet.' }); return }

  try {
    const content = itinerary.content as unknown as ItineraryContent
    const memberNames = trip.members.map((m) => m.user.name)

    const pdf = await buildItineraryPDF(
      trip.name,
      trip.destination,
      trip.travelStart,
      trip.travelEnd,
      memberNames,
      content,
    )

    const filename = `${trip.name.replace(/[^a-z0-9]/gi, '_')}_itinerary.pdf`
    res.setHeader('Content-Type', 'application/pdf')
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`)
    res.send(pdf)
  } catch (err) {
    console.error('[PDF]', err)
    res.status(500).json({ error: 'Failed to generate PDF.' })
  }
})

// GET /api/trips/:id/export/ics — download .ics calendar file
exportRouter.get('/trips/:id/export/ics', requireAuth, async (req: AuthRequest, res) => {
  const tripId = String(req.params.id)

  const trip = await prisma.trip.findUnique({
    where: { id: tripId },
    include: {
      members: { where: { inviteStatus: 'ACCEPTED' }, include: { user: { select: { name: true } } } },
    },
  })
  if (!trip) { res.status(404).json({ error: 'Trip not found' }); return }

  const isMember = trip.members.some((m) => (m as any).userId === req.userId)
  if (!isMember) { res.status(403).json({ error: 'Not a member.' }); return }

  const itinerary = await prisma.itinerary.findFirst({
    where: { tripId },
    orderBy: { version: 'desc' },
  })

  const content = itinerary?.content as unknown as ItineraryContent | undefined
  const start = trip.travelStart ?? new Date()
  const end   = trip.travelEnd   ?? new Date(start.getTime() + (content?.tripDuration ?? 3) * 86400000)

  const toArr = (d: Date): [number, number, number] =>
    [d.getFullYear(), d.getMonth() + 1, d.getDate()]

  const { error, value } = createEvents([
    {
      title:       `✈️ ${trip.name} — ${trip.destination}`,
      start:       toArr(start),
      end:         toArr(end),
      startInputType: 'local',
      endInputType:   'local',
      description: content
        ? `${content.conflictSummary}\n\nRecommended dates: ${content.recommendedDates}\n\nGenerated by TripUntangle AI.`
        : `Trip to ${trip.destination}. Generated by TripUntangle AI.`,
      location: trip.destination,
      url:      process.env.FRONTEND_URL ?? 'http://localhost:5173',
      attendees: trip.members.map((m) => ({ name: m.user.name })),
    },
  ])

  if (error || !value) {
    res.status(500).json({ error: 'Failed to generate calendar file.' })
    return
  }

  const filename = `${trip.name.replace(/[^a-z0-9]/gi, '_')}.ics`
  res.setHeader('Content-Type', 'text/calendar; charset=utf-8')
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`)
  res.send(value)
})

// GET /api/trips/:id/ooo — generate OOO email draft
exportRouter.get('/trips/:id/ooo', requireAuth, async (req: AuthRequest, res) => {
  const tripId = String(req.params.id)

  const trip = await prisma.trip.findUnique({
    where: { id: tripId },
    include: {
      members: { where: { inviteStatus: 'ACCEPTED' }, include: { user: { select: { name: true } } } },
    },
  })
  if (!trip) { res.status(404).json({ error: 'Trip not found' }); return }

  const isMember = trip.members.some((m) => (m as any).userId === req.userId)
  if (!isMember) { res.status(403).json({ error: 'Not a member.' }); return }

  const itinerary = await prisma.itinerary.findFirst({
    where: { tripId },
    orderBy: { version: 'desc' },
  })
  const content = itinerary?.content as unknown as ItineraryContent | undefined

  try {
    const memberNames = trip.members.map((m) => m.user.name)
    const ooo = await generateOOO(
      trip.name,
      trip.destination,
      content?.recommendedDates ?? 'upcoming dates',
      memberNames,
    )
    res.json({ ooo })
  } catch (err) {
    console.error('[OOO]', err)
    res.status(500).json({ error: 'Failed to generate OOO.' })
  }
})
